### ISSUE TITLE
Refreshing All Pants Projects makes Project explorer unusable

### ISSUE THREAD

**Issue by mkralka** [pantsbuild/intellij-pants-plugin#118] opened 2016-04-07 18:08 UTC
Pants Plugin Version: 1.3.15
Intellij version: 15.0.5

After clicking on the "Refresh All Pants Projects" button on the Pants tool window, the Project explorer (⌘1 on Mac) becomes unusable, requiring a restart of Intellij to recover. After refreshing, the project explorer is revealed and root directory of one of pants projects is selected.

Dismissing the Project explorer causes it to re-open. Selecting a file or directory causes it to snap back to  originally selected pants project root directory. At this point, it's impossible to dismiss the project explorer  or use the project explorer to open files.

Rolling back to 1.3.14 and the problem goes away.

**Comment by wisechengyi** [comment] 2016-04-07 18:13
You might want to try freshly re-import the project. There are some issues with 'refresh' as it has become a little stale.

**Comment by mkralka** [comment] 2016-04-07 21:21
Although probably overkill, I cleaned up all intellij and pants files and started again from scratch.

That seems to have addressed the issue. Thanks!

If you have no plans to fix the refresh, feel free to close this issue.

**Comment by mkralka** [comment] 2016-04-07 22:10
I spoke too soon. Even after starting from scratch, I'm still seeing the behavior.

**Comment by wisechengyi** [comment] 2016-04-07 23:03
Oh that could be caused by dfa414a8aa21434463b9bfeb0954ca277c12e1c5. Do you have multiple projects imported? 
![screen shot 2016-04-07 at 4 03 05 pm](https://cloud.githubusercontent.com/assets/596358/14369479/3f2b2fac-fcda-11e5-8e1c-3ff4ae31271b.png)

**Comment by mkralka** [comment] 2016-04-07 23:42
Ah, yes.

After I imported 1 project, it worked fine. After importing the rest of my projects, it starting misbehaving again.

**Comment by wisechengyi** [comment] 2016-04-07 23:43
I've attached a hot fix. This GUI issue is not always reproducible for me. Please let me know if that works.
To install: Preferences -> plugin -> install plugin from disk -> choose the zip
[pants_view_fix.zip](https://github.com/pantsbuild/intellij-pants-plugin/files/209391/pants_view_fix.zip)

diff: https://github.com/pantsbuild/intellij-pants-plugin/compare/master...wisechengyi:view_fix?expand=1

**Comment by mkralka** [comment] 2016-04-08 03:07
The fix worked for me! Thanks!

**Comment by wisechengyi** [comment] 2016-04-18 18:32
merged 9c8e5820fdd4e1dba727fc953f0ec09c2320f161
pending 1.3.16 release

**Closed by wisechengyi** 2016-04-18 18:32 UTC
