### ISSUE TITLE
thread leak error in CI

### ISSUE THREAD

**Issue by wisechengyi** [pantsbuild/intellij-pants-plugin#130] opened 2016-05-03 22:41 UTC
since 2016 change, CI is broken due to thread leak. ticket filed at https://youtrack.jetbrains.com/issue/IDEA-155496

**Comment by wisechengyi** [comment] 2016-05-04 07:07
ThreadTracker.java has many changes lately. 

Also the check was disabled essentially disabled in IDEA 15.

```
[tw-mbp-yic intellij-community ((pycharm/145.607))]$ git diff master platform/testFramework/src/com/intellij/testFramework/ThreadTracker.java
diff --git a/platform/testFramework/src/com/intellij/testFramework/ThreadTracker.java b/platform/testFramework/src/com/intellij/testFramework/ThreadTracker.java
index 5ed6d1a..b2844e6 100644
--- a/platform/testFramework/src/com/intellij/testFramework/ThreadTracker.java
+++ b/platform/testFramework/src/com/intellij/testFramework/ThreadTracker.java
@@ -15,13 +15,12 @@
  */
 package com.intellij.testFramework;
 
-import com.intellij.execution.process.ProcessIOExecutorService;
 import com.intellij.openapi.Disposable;
 import com.intellij.openapi.application.ApplicationManager;
 import com.intellij.openapi.project.ProjectManager;
 import com.intellij.openapi.project.impl.ProjectManagerImpl;
+import com.intellij.openapi.util.Condition;
 import com.intellij.openapi.util.Disposer;
-import com.intellij.openapi.util.ShutDownTracker;
 import com.intellij.util.ReflectionUtil;
 import com.intellij.util.WaitFor;
 import com.intellij.util.containers.ContainerUtil;
@@ -54,7 +53,7 @@ public class ThreadTracker {
   private static final Method getThreads = ReflectionUtil.getDeclaredMethod(Thread.class, "getThreads");
 
   @NotNull
-  public static Collection<Thread> getThreads() {
+  private static Collection<Thread> getThreads() {
     Thread[] threads;
     try {
       // faster than Thread.getAllStackTraces().keySet()
@@ -66,11 +65,15 @@ public class ThreadTracker {
     return ContainerUtilRt.newArrayList(threads);
   }
 
-  private static final Set<String> wellKnownOffenders = new THashSet<>();
+  private static final Set<String> wellKnownOffenders = new THashSet<String>();
   static {
+        wellKnownOffenders.add("Action Updater"); // todo remove
+        wellKnownOffenders.add("Alarm pool(own)");
+        wellKnownOffenders.add("Alarm pool(shared)");
     wellKnownOffenders.add("AWT-EventQueue-");
     wellKnownOffenders.add("AWT-Shutdown");
     wellKnownOffenders.add("AWT-Windows");
+        wellKnownOffenders.add("Change List Updater"); //todo remove
     wellKnownOffenders.add("CompilerThread0");
     wellKnownOffenders.add("Finalizer");
     wellKnownOffenders.add("IDEA Test Case Thread");
@@ -79,12 +82,14 @@ public class ThreadTracker {
     wellKnownOffenders.add("JobScheduler FJ pool ");
     wellKnownOffenders.add("JPS thread pool");
     wellKnownOffenders.add("Keep-Alive-Timer");
+        wellKnownOffenders.add("Low Memory Detector");
     wellKnownOffenders.add("main");
     wellKnownOffenders.add("Monitor Ctrl-Break");
-    wellKnownOffenders.add("Netty ");
     wellKnownOffenders.add("Reference Handler");
     wellKnownOffenders.add("RMI TCP Connection");
     wellKnownOffenders.add("Signal Dispatcher");
+    wellKnownOffenders.add("Netty ");
+        wellKnownOffenders.add("timed reference disposer");
     wellKnownOffenders.add("timer-int"); //serverImpl
     wellKnownOffenders.add("timer-sys"); //clientimpl
     wellKnownOffenders.add("TimerQueue");
@@ -93,27 +98,28 @@ public class ThreadTracker {
     wellKnownOffenders.add("VM Thread");
     wellKnownOffenders.add("YJPAgent-Telemetry");
 
-    longRunningThreadCreated(ApplicationManager.getApplication(),
-                             "Periodic tasks thread",
-                             "ApplicationImpl pooled thread ",
-                             ProcessIOExecutorService.POOLED_THREAD_PREFIX);
+    longRunningThreadCreated(ApplicationManager.getApplication(), "Periodic tasks thread", "ApplicationImpl pooled thread");
   }
 
   // marks Thread with this name as long-running, which should be ignored from the thread-leaking checks
   public static void longRunningThreadCreated(@NotNull Disposable parentDisposable,
                                               @NotNull final String... threadNamePrefixes) {
     wellKnownOffenders.addAll(Arrays.asList(threadNamePrefixes));
-    Disposer.register(parentDisposable, () -> wellKnownOffenders.removeAll(Arrays.asList(threadNamePrefixes)));
+    Disposer.register(parentDisposable, new Disposable() {
+      @Override
+      public void dispose() {
+        wellKnownOffenders.removeAll(Arrays.asList(threadNamePrefixes));
+      }
+    });
   }
 
   @TestOnly
   public void checkLeak() throws AssertionError {
     NettyUtil.awaitQuiescenceOfGlobalEventExecutor(100, TimeUnit.SECONDS);
-    ShutDownTracker.getInstance().waitFor(100, TimeUnit.SECONDS);
     try {
       if (myDefaultProjectInitialized != ((ProjectManagerImpl)ProjectManager.getInstance()).isDefaultProjectInitialized()) return;
 
-      Collection<Thread> after = new THashSet<>(getThreads());
+      Collection<Thread> after = new THashSet<Thread>(getThreads());
       after.removeAll(before);
 
       for (final Thread thread : after) {
@@ -121,7 +127,12 @@ public class ThreadTracker {
         ThreadGroup group = thread.getThreadGroup();
         if (group != null && "system".equals(group.getName()))continue;
         final String name = thread.getName();
-        if (ContainerUtil.exists(wellKnownOffenders, name::contains)) {
+        if (ContainerUtil.exists(wellKnownOffenders, new Condition<String>() {
+          @Override
+          public boolean value(String pattern) {
+            return name.contains(pattern);
+          }
+        })) {
           continue;
         }
 
@@ -142,12 +153,7 @@ public class ThreadTracker {
           continue; // ignore threads with empty stack traces for now. Seems they are zombies unwilling to die.
         }
 
-        if (isIdleApplicationPoolThread(thread, stackTrace)) {
-          continue;
-        }
-
-        @SuppressWarnings("NonConstantStringShouldBeStringBuffer")
-        String trace = "Thread leaked: " + thread + "; " + thread.getState() + " (" + thread.isAlive() + ")\n--- its stacktrace:\n";
+        String trace = "Thread leaked: " + thread+"; " + thread.getState()+" ("+ thread.isAlive()+")\n--- its stacktrace:\n";
         for (final StackTraceElement stackTraceElement : stackTrace) {
           trace += " at "+stackTraceElement +"\n";
         }
@@ -160,22 +166,15 @@ public class ThreadTracker {
     }
   }
 
-  // true if somebody started new thread via "executeInPooledThread()" and then the thread is waiting for next task
-  private static boolean isIdleApplicationPoolThread(Thread thread, StackTraceElement[] stackTrace) {
-    if (!thread.getName().startsWith("ApplicationImpl pooled thread ")) return false;
-    boolean insideTPEgetTask = Arrays.stream(stackTrace)
-      .anyMatch(element -> element.getMethodName().equals("getTask")
-                           && element.getClassName().equals("java.util.concurrent.ThreadPoolExecutor"));
-
-    return insideTPEgetTask;
-  }
-
   public static void awaitThreadTerminationWithParentParentGroup(@NotNull final String grandThreadGroup, int timeout, @NotNull TimeUnit unit) {
     long start = System.currentTimeMillis();
     while (System.currentTimeMillis() < start + unit.toMillis(timeout)) {
-      Thread jdiThread = ContainerUtil.find(getThreads(), thread -> {
-        ThreadGroup group = thread.getThreadGroup();
-        return group != null && group.getParent() != null && grandThreadGroup.equals(group.getParent().getName());
+      Thread jdiThread = ContainerUtil.find(getThreads(), new Condition<Thread>() {
+        @Override
+        public boolean value(Thread thread) {
+          ThreadGroup group = thread.getThreadGroup();
+          return group != null && group.getParent() != null && grandThreadGroup.equals(group.getParent().getName());
+        }
       });
```

**Comment by peiyuwang** [comment] 2016-05-04 07:23
Could be, another possibility is the fact that leaking thread is related _Timer-_ and I couldn't reproduce this locally, suggests might be related to slower build on travis, Timer only gets triggered at certain time when build is slow enough.

Either way might be a problem already exists from `15`, only surfaced through this upgrade.

I assigned our own thread a name prefix and confirmed it's not that.

**Comment by wisechengyi** [comment] 2016-05-04 07:46
`IJ_ULTIMATE=true ./scripts/run-tests-ci.sh` consistently reproduces the leak error for me but on nondeterministic test(s).

Another example from https://travis-ci.org/wisechengyi/intellij-pants-plugin/jobs/127662672
```
                     1) testScopedJUnitTests(com.twitter.intellij.pants.integration.OSSPantsTestExamplesIntegrationTest)
                     java.lang.AssertionError: Thread leaked: Thread[BaseDataReader: error stream of java,4,main]; RUNNABLE (true)
                     --- its stacktrace:
                      at java.io.FileInputStream.readBytes(Native Method)
                      at java.io.FileInputStream.read(FileInputStream.java:246)
                      at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
                      at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
                      at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
                      at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
                      at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
                      at java.io.InputStreamReader.read(InputStreamReader.java:184)
                      at java.io.Reader.read(Reader.java:140)
                      at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:99)
                      at com.intellij.util.io.BaseOutputReader.readAvailable(BaseOutputReader.java:146)
                      at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:130)
                      at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:61)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                      at java.lang.Thread.run(Thread.java:745)
```

**Comment by peiyuwang** [comment] 2016-05-08 23:14
https://rbcommons.com/s/twitter/r/3819/ addressed the thread leak (temporarily) treating as an upstream issue for now

https://rbcommons.com/s/twitter/r/3831/ addressed another test failure, most likely irrelevant.

Closing.

**Closed by peiyuwang** 2016-05-08 23:14 UTC
Labels: bug
