### ISSUE TITLE
Stopping a running app in debugger, doesn't kill the app

### ISSUE THREAD

**Issue by JasonRosenberg** [pantsbuild/intellij-pants-plugin#59] opened 2015-10-15 22:51 UTC
I set up a run config in IntelliJ, which runs a pants target correctly, within the debugger. It's a long-running server (not a unit test).  Normally, to stop running such an app in the debugger, I can hit the red square Stop icon.  However, in this case, it only seems to disconnect the debugger from the window, but doesn't actually stop the app, nor the underlying python processes that call 'pants run'.  So, the next time I try to run the app in the debugger, I get a 'port address already in use', since the previous invocation is actually still running.

**Comment by ericzundel** [comment] 2015-10-16 12:26
We are using Plugin version 13.5 and  pants version 0.0.53-square-20151012-01, which is public release 0.0.53 plus a few more commits.

I just ran `./pants run <service> --jvm-debug` from the command line and attached remotely.  The behavior is the same and I think this is by design.

**Comment by wisechengyi** [comment] 2015-12-15 08:39
this should be fixed by https://github.com/pantsbuild/intellij-pants-plugin/commit/4eca8209fcfce03a0e792e77f2cfadbbe28f53a3

**Comment by wisechengyi** [comment] 2016-03-08 18:58
https://rbcommons.com/s/twitter/r/3510/ for the intellij junit runner

**Comment by wisechengyi** [comment] 2016-03-17 07:48
fixed at 1.3.14 https://plugins.jetbrains.com/plugin/7412

**Closed by wisechengyi** 2016-03-17 07:48 UTC
